name: Concurrency
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docker build..."

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    concurrency:
      group: production-deployment
      cancel-in-progress: true   

    steps:
      - run: echo "Deploying..."
      - run: sleep 600
