name: Generate ASCII - Multi Jobs (After Fix)
on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: Generate dragon.txt file
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" > dragon.txt

      - name: Upload dragon.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt


  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Test file content
        run: grep -i "dragon" dragon.txt


  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon.txt artifact
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file

      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying ...."
